### ISSUE TITLE
Map property structure to a class

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#15]
From a conversation with @Gnat008. As an example, PerWorldInventory uses a worlds.yml config with arbitrary entries:
```yml
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
```

We could map the YAML to a provided JavaBeans class...
