### ISSUE TITLE
How do I get all the keys in a ConfigurationSection with ConfigMe?

### ISSUE THREAD

**Issue by AshuGuptaGamer** [AuthMe/ConfigMe#157]
I wanna get all the keys in a section, without making it default.

Code:
```
some-secton:
  key-1:
    Test: "Hello"
  key-2:
    Test: "Yoo My Boii"
```

So I wanna get all the keys so I can grab the values
