### ISSUE TITLE
Create a Map of Map

### ISSUE THREAD

**Issue by MarkinMarker** [AuthMe/ConfigMe#179]
Hey, I am trying to create a property that is a `Map<String, Map<String, Bean>`, but I can't figure how. 
To result in:  
```yaml
path:
  map1:
    child-map1:
      text: Text
    child-map2:
      text: Text
   map2:
   #etc
```
All I can think of is is having a Map of String and Bean, and inside the Bean have another map of String and other bean. But this will create one path more than needed.
