### ISSUE TITLE
MapProperty requires non empty path

### ISSUE THREAD

**Issue by Sxtanna** [AuthMe/ConfigMe#191]
MapProperty does not generate default values when it's path is an empty String.

ex. Bean
```java
class Info {
    String       name;
    List<String> lore;
}
```

ex. Property
```java
public static final MapProperty<Info> INFO = mapProperty(BeanPropertyType.of(Info.class))
.path("")
.defaultEntry("basic", new Info("hello", Arrays.asList("world")))
.build()
```

produces an empty file, while modifying path to be `path("test")` produces expected output of 

```yaml
test:
  basic:
    name: "hello"
    lore:
      - "world"
```
