### ISSUE TITLE
Saving property at root path ("") results in invalid YAML

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#20]
If a property is set at the root (bean property with path `""`) saving the configuration will result in invalid YAML (first colon):
```yml
: # <-- parse error
    firstBeanField: true
    secondBeanField: 13
```
