### ISSUE TITLE
List of key-value pairs

### ISSUE THREAD

**Issue by EbonJaeger** [AuthMe/ConfigMe#214]
Perhaps more of just a question than an issue, but in a config I would like to have a list of key-value pairs, for example:
```yaml
homes:
  limit-permissions:
    - example.node: 10
    - example.node.other: 20
```

I tried using a `MapProperty`, but that doesn't seem to do what I want; it expects `{ebonhomes.limits.example2=20, ebonhomes.limits.example=10}`.

I could just do a list of Strings and split on `:`, but that's ugly, and I'd really not have to do that.

Is there something here that I missed that'll do what I want?

**Comment by ljacqu** [comment]
Sorry for only answering now—feel free to ping me if I don't get back to issues after 7 days because when that happens, 95% of the time it's because I somehow didn't see it :( 

I see what you're trying to do and it would work for strings with no dots in them. Dots are an alternative way to delimit paths, so the following two YAML excerpts are loaded the same way in ConfigMe's eyes:
```yaml
homes.limits.test: 5
```
```yaml
homes:
  limits:
    test: 5
```

Probably for your use case it would be enough to have a configurable way to turn this off?

**Comment by EbonJaeger** [comment]
Crap, I forgot that dots are special in YAML. It's been a while... I usually work with TOML these days lol

Actually, specifying permission nodes like 
```yaml
homes:
  limits:
    blah: 10
```
 should probably work... No reason they have to be a single string. I guess the question then becomes "how to I access them?"

I guess it would just be a list, right? Or would it be a map... Or I'm way off.
