### ISSUE TITLE
Overlapping property with root property "" creates invalid YAML

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#363]
Reported by Wector11211—

Defining a property at empty string `""` and another one like path `"enabled"` will result in invalid YAML being produced:
```yaml
? ''
:   foo:
        # Comment that is present on all instances
        servers: []
    bar:
        # Comment that is present on all instances
        servers: []
enabled: true
```

I confirmed that this worked in 1.3. Expected would be an exception just like when two properties use the same path, or one property has a conflict with another property (like `foo.bar` and `foo.bar.baz`)
