### ISSUE TITLE
Question: Nested bean serialization (Example: Minecraft chat)

### ISSUE THREAD

**Issue by games647** [AuthMe/ConfigMe#55]
Minecraft chat uses [JSON](http://wiki.vg/Chat#Inheritance). This allows advanced chat formatting like specifying hover and click events. I'm trying to build the same thing in YAML to make use of comments and explicit message keys. 

Example YAML. (Valid YAML according to [Online-Parser](https://yaml-online-parser.appspot.com/)):
```yaml
message-key:
  color: blue
  text: outside
  bold: true
  extra:
    - color: green
      text: inner1
      italic: true
    - color: blue
      text: inner2
```

But if I try to save it with the Bean example. It builds something like this below. 

Output
```yml
message-key:
    color: 'blue'
    extra: 
    - !!ChatComponent
    color: yellow
    extra: null
    text: inner
    text: 'outside'
```

Bean:
```java
public class ChatComponent {

    private String color;
    private String text;
    private List<ChatComponent> extra;

//setters and getters
...
}
```

Settings class
```java
    public static final Property<Component> TEST =
        newBeanProperty(ChatComponent.class, "message-key", initComponent());

    private static ChatComponent initComponent() {
        ChatComponent comp = new ChatComponent();
        comp("green");
        comp("outside");

        List<Component> extras = new ArrayList<>();

        ChatComponent extra = new ChatComponent();
        extra.setColor("yellow");
        extra.setText("inner");
        extras.add(extra);

        comp.setExtras(extras);
        return comp;
    }
```

**Comment by ljacqu** [comment]
Probably the combination of bean type with collection isn't supported. I'll cook up a test case and will try to implement it. :)

**Comment by ljacqu** [comment]
Initial analysis: as assumed, support for collections isn't great. The entire "extra" field is not split further and exported as SnakeYAML does by default. And that is exactly this:
```yml
    - !!ChatComponent
    color: yellow
    extra: null
    text: inner
```

which explains the weird output and the wrong indentation. So what I need to do is be aware of the collection type and generically decide whether it needs to be visited further, or if it's OK to export the entries directly (e.g. for string list).
