### ISSUE TITLE
Improve behavior of String collection properties

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#58]
Right now as soon as one entry is not a String in the read data, the entire list will not be returned and the default value will be returned instead. So a property like `newStringList("my.path", "default", "values")` will return a List["default", "values"] for:
```yml
my:
  path:
    - 'a string'
    - 5
    - 'another string'
```

while it would make more sense to return a List["a string", "5", "another string"].
