### ISSUE TITLE
Allow to provide comments for sections

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#6]
Currently we can write comments in config.yml for properties with `@Comment`, but not above sections:

```yml
settings:
    section1:
        # This is a property so we can do a comment here, but not above
        setting: false
```

Implement a way to add such comments. Annotations at type level would be nice but we can only add one annotation per element. Since all settings classes implement `SettingsHolder` we could put a method `Map<String, String> getSectionComments()` on there, for example.
