### ISSUE TITLE
Support concatenated paths in YML file

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#71]
For a yaml file like so:

```yaml
commands:
    authme.register:
        description: 'Register a player'
```

the root Map in the YamlReader will be initialized with one entry `command`, containing one child with key "authme.register", instead of those two being two separate nodes. This means that it is then not possible to read such values anymore, as doing `getObject("commands.authme.register.description")` will split the path by periods and try to retrieve individual children.
